/**
 * This file was automatically generated by SMASH v2.0 ( https://smashlabs.io )
 */

'use strict';

/**
 * Creates an instance of HttpRequest
 */
class HttpRequest {
    constructor() {
        this.method = null;
        this.headers = {};
        this.queryUrl = null;
        this.formData = null;
        this.form = null;
        this.username = null;
        this.password = null;
        this.body = null;
    }
}

module.exports = HttpRequest;
