/**
 * This file was automatically generated by SMASH v2.0 ( https://smashlabs.io )
 */

'use strict';

/**
 * Creates an instance of HttpResponse
 */
class HttpResponse {
    constructor() {
        this.statusCode = null;
        this.body = null;
        this.headers = null;
    }
}

module.exports = HttpResponse;
