/**
 * This file was automatically generated by SMASH v2.0 ( https://smashlabs.io )
 */

'use strict';

/**
 * Creates an instance of HttpContext.
 */
class HttpContext {
    constructor() {
        this.request = null;
        this.response = null;
    }
}

module.exports = HttpContext;
